export const LOGIN_EXITOSO  = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'  

//Para manejar contactos
export const OBTENER_CONTACTOS = 'OBTENER_CONTACTOS'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const CREATE_CONTACT = 'CREATE_CONTACT'
export const UPDATE_CURRENT_CONTACT = 'UPDATE_CURRENT_CONTACT'
export const DELETE_CURRENT_CONTACT = 'DELETE_CURRENT_CONTACT'
export const FILTRAR_CONTACTOS = 'FILTRAR_CONTACTOS'
export const FILTER_FORM = 'FILTER_FORM'
export const DELETE_FILTER = 'DELETE_FILTER'
export const OBTENER_CONTACT_CHANNELS = 'OBTENER_CONTACT_CHANNELS'
export const DELETE_CONTACT_CHANNELS = 'DELETE_CONTACT_CHANNELS'
//Para manejar regiones
export const OBTENER_REGIONES = 'OBTENER_REGIONES'
export const ERROR_OBTENER_REGIONES = 'ERROR_OBTENER_REGIONES'
export const OBTENER_REGIONES_FORMULARIO = 'OBTENER_REGIONES_FORMULARIO'
export const OBTENER_PAISES_DE_REGION = 'OBTENER_PAISES_DE_REGION'
export const OBTENER_CIUDADES_DE_PAIS = 'OBTENER_CIUDADES_DE_PAIS'
export const OBTENER_COMPANIAS = 'OBTENER_COMPANIAS'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const UPDATE_CURRENT_COMPANY = 'UPDATE_CURRENT_COMPANY'
export const DELETE_CURRENT_COMPANY = 'DELETE_CURRENT_COMPANY'
export const SELECCIONAR_REGION = 'SELECCIONAR_REGION'
export const SELECCIONAR_PAIS = 'SELECCIONAR_PAIS'
export const SELECCIONAR_CIUDAD = 'SELECCIONAR_CIUDAD'
export const DELETE_CIUDADES_DE_PAIS = 'DELETE_CIUDADES_DE_PAIS'
//Para manejar usuarios
export const OBTENER_USUARIOS = "OBTENER_USUARIOS"
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER"
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER"
export const DELETE_USER = "DELETE_USER"